# Generated by Django 5.2.7 on 2025-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('winner', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')])),
                ('players_team1', models.ManyToManyField(related_name='team1_matches', to='players.player')),
                ('players_team2', models.ManyToManyField(related_name='team2_matches', to='players.player')),
            ],
        ),
    ]
