# Generated by Django 5.2.7 on 2025-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=8.333)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
